version: "3"
services:
  agent_service:
    build: .
    container_name: agent_service_container
    ports:
      - "8000:8000"
    restart: always
    environment:
      OPENAI_API_KEY: "${OPENAI_API_KEY}"

  mydb:
    image: mysql:8.0
    container_name: mydb_container
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      TZ: "Asia/Seoul"
    ports:
      - "3306:3306"
    restart: always
